# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='manufacturer_info',
            field=models.CharField(default='empty_info', max_length=3000),
            preserve_default=False,
        ),
    ]
