# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 10:58
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0002_manufacturer_manufacturer_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneproduct',
            name='battery',
            field=models.CharField(help_text='Пример: 3260 мАч', max_length=30, verbose_name='Емкость батареи'),
        ),
        migrations.AlterField(
            model_name='phoneproduct',
            name='camera',
            field=models.CharField(help_text='Пример: 13/5 МП', max_length=40, verbose_name='Камера'),
        ),
        migrations.AlterField(
            model_name='phoneproduct',
            name='chipset',
            field=models.CharField(help_text='Пример: MediaTek Helio P10', max_length=60, verbose_name='Чипсет'),
        ),
        migrations.AlterField(
            model_name='phoneproduct',
            name='description',
            field=models.CharField(help_text='Пример: Опиши меня красиво', max_length=3000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='phoneproduct',
            name='in_stock',
            field=models.BooleanField(default=True, verbose_name='Наличие'),
        ),
        migrations.AlterField(
            model_name='phoneproduct',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop.Manufacturer', to_field='manufacturer_name', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='phoneproduct',
            name='os_version',
            field=models.CharField(help_text='Пример: Google Android 6.0, Flyme 5.2.4.0G', max_length=50, verbose_name='Операцйионная система'),
        ),
        migrations.AlterField(
            model_name='phoneproduct',
            name='phone_RAM_memory',
            field=models.CharField(help_text='Пример: 2/3 ГБ ОЗУ', max_length=40, verbose_name='Оперативная память'),
        ),
        migrations.AlterField(
            model_name='phoneproduct',
            name='phone_memory',
            field=models.CharField(help_text='Пример: 16/32 ГБ встроенная память', max_length=40, verbose_name='Постоянная память'),
        ),
        migrations.AlterField(
            model_name='phoneproduct',
            name='phone_model',
            field=models.CharField(help_text='Пример: Meizu U20', max_length=30, verbose_name='Модель телефона'),
        ),
        migrations.AlterField(
            model_name='phoneproduct',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='RUB', max_digits=100, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='phoneproduct',
            name='size',
            field=models.CharField(help_text='Пример: 153x75x8.2 мм', max_length=40, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='phoneproduct',
            name='size_screen',
            field=models.CharField(help_text='Пример: 5.5 дюйма FullHD IPS', max_length=40, verbose_name='Размер экрана'),
        ),
        migrations.AlterField(
            model_name='phoneproduct',
            name='sku',
            field=models.CharField(help_text='Пример: 107654', max_length=15, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='phoneproduct',
            name='stock',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='Осталось'),
        ),
        migrations.AlterField(
            model_name='phoneproduct',
            name='weight',
            field=models.CharField(help_text='Пример: 158 грамм', max_length=20, verbose_name='Вес'),
        ),
    ]
